# Generated by Django 4.1.7 on 2023-03-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=20)),
                ('image_file', models.ImageField(upload_to='items/')),
            ],
        ),
    ]
